---
# Installing yum modules on Linux using Ansible Playbook
- name: Install Required Packages on CentOS
  hosts: localhost
  connection: local

  tasks:
    - name: Install CentOS Software Collections 
      yum:
        name: centos-release
        state: present
      ignore_errors: yes

    - name: Install Apache HTTP Server
      yum:
        name: httpd24-httpd
        state: present

    - name: Install PHP 7.3 and Required Modules
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - rh-php73
        - rh-php73-php
        - rh-php73-php-mbstring
        - rh-php73-php-mysqlnd
        - rh-php73-php-gd
        - rh-php73-php-xml

    - name: Install MariaDB Server
      yum:
        name: mariadb-server
        state: present

    - name: Install MariaDB Client
      yum:
        name: mariadb
        state: present